---
title: "Loops And Functions"
author: "Clarissa Boyajian"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task 1
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

transects <- c("Transect A", "Transect B", "Transect C")

weekday_transects <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
    cell <- paste(weekdays[i], "-", transects[j])
    weekday_transects[i, j] <- cell
  }
}
```

## Task 2
```{r}
force <- function(mass, accel) {
  mult_force <- mass * accel
  return(paste("The resulting force is", mult_force, "Newtons."))
}

force(mass = 20, accel = 50)
```

# Taks 3
```{r}
name_column <- function(df_name, df_num) {
  
  if (df_num < 1) {
    warning("Column number is less than 1.")
  }
 else if (df_num > ncol(df_name)) {
    stop("Column number is higher than number of columns in data frame.")
  }
  colnames(df_name[df_num])
}

name_column(df_name = mtcars, df_num = 0)
```

# Task 4
```{r}
fish_parms <- data.frame(sci_name = c("Chanos chanos", "Sphyraena barracuda", "Caranx ignobilis"),
                         common_name = c("Milkfish", "Great barracuda", "Giant trevally"),
                         a_est = c(0.0905, 0.0181, 0.0353),
                         b_est = c(2.52, 3.27, 3.05))

fish_weight <- function(fish_name, tot_length) {
  fish_select <- fish_parms %>% 
    filter(common_name == fish_name)
  fw <- fish_select$a_est * (tot_length ^ fish_select$b_est)
  return(fw)
}

fish_weight(fish_name = "Giant trevally", tot_length = 10)


length_vec <- seq(from = 0, to = 100, by = 1)

milkfish_weights <- fish_weight(fish_name = "Milkfish", length_vec)

milkfish_weights
```

## Task 5
```{r}
wave_power <- function(wave_height, wave_period) {
  p <- 0.5 * (wave_height ^ 2) * wave_period
  return(p)
}

height_vec <- seq(from = 0, to = 3, by = 0.2)

wave_power(wave_height = height_vec, wave_period = 8)
```

```{r}
wave_power_2 <- function(wave_height, wave_period, water_depth) {
  if (water_depth < 12) {
    p <- 0.81 * (wave_height ^ 2) * wave_period
    message("Shallow water equation used.")
  }
  else if (water_depth > 12) {
    p <- 0.5 * (wave_height ^ 2) * wave_period
    message("Deep water equation used.")
  }
  return(p)
}

wave_power_2(wave_height = 1, wave_period = 1, water_depth = 1)

```





